baseURL = "https://exp-ai.com/"
languageCode = "en-us"
theme = "airspace-hugo"
title = "Exp-AI"
[[menu.footer]]
name = "About us"
url = "https://exp-ai.com/#intro"
weight = 1
[params]
date_format = "2006-01-06T00:00:00+00:00"
home = "Home"
[params.blog]
enable = true
subtitle = "Catch up with us, anytime and anywhere"
title = "Get The Latest On What We're doing"
[params.call]
enable = true
paragraph = "Together, we can make your ideas become your business main drive!"
title = "Let us drive you to the new AI-leveraged era"
[params.contact]
enable = true
subtitle = "The cognitive era is coming, making your ideas your business' best asset. We can help you making them true."
title = "Just drop us a note!"
[params.contact.box]
address = "North Main Street, Brooklyn Australia"
email = "Email: contact@mail.com"
phone = "Phone: +88 01672 506 744"
title = "Stop by for a visit"
[params.contact.form]
button = "Send message"
email = "Your email"
message = "Your message"
name = "Your name"
subject = "Your subject"
[params.contact.gmaps]
title = "We Also Count in Google Maps"
[params.feature]
content = "In this new opening paradigm, ideas are becoming the most valuable asset of the human species. Do you have any? Let's talk!<br/><br/>We love making great ideas true!"
enable = true
title = "We believe in great ideas"
[params.feature.button]
caption = "Contact Us"
url = "/contact/"
[params.slider]
enable = true
subtitle = "<div style=\"text-align:center;width:100%\">AI&ndash;leveraged solutions for the modern world.</div>"
title = "<div style=\"text-align:center;width:100%\">Exp&mdash;AI</div>"
[params.wrapper]
enable = true
italic = "\"Many of life's failures are people who did not realize how close they were to success when they gave up.\" - Thomas Alva Edison"
paragraph = "Exp-AI is born as an association of former scientists and serial entrepeneurs with a common goal: bring companies closer to the new cognitive era with tailored solutions, specifically designed to get the best possible outcome out of every process and endeavor."
title = "About Us"
