baseURL = "https://danielperezr88.github.io/"
languageCode = "en-us"
theme = "airspace-hugo"
title = "Exp-AI"
[[menu.footer]]
name = "Terms"
url = "#"
weight = 5
[[menu.footer]]
name = "Blog"
url = "#"
weight = 4
[[menu.footer]]
name = "How it works"
url = "#"
weight = 3
[[menu.footer]]
name = "Contact us"
url = "#"
weight = 2
[[menu.footer]]
name = "About us"
url = "#"
weight = 1
[[menu.header]]
name = "Contact"
url = "/contact"
weight = 5
[[menu.header]]
name = "Service"
url = "/service"
weight = 4
[[menu.header]]
name = "Blog"
url = "/blog"
weight = 3
[[menu.header]]
name = "Work"
url = "/work"
weight = 2
[params]
date_format = "2006-01-06T00:00:00+00:00"
home = "Home"
[params.blog]
enable = true
subtitle = "Catch up with us, anytime and anywhere"
title = "Get The Latest On What We're doing"
[params.call]
enable = true
paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."
title = "We design delightful digital experiences."
[params.contact]
enable = true
subtitle = "Don’t just take our word for it. Check out some of our latest work."
title = "Drop us a note"
[params.contact.box]
address = "North Main Street, Brooklyn Australia"
email = "Email: contact@mail.com"
phone = "Phone: +88 01672 506 744"
title = "Stop by for a visit"
[params.contact.form]
button = "Send message"
email = "Your email"
message = "Your message"
name = "Your name"
subject = "Your subject"
[params.contact.gmaps]
title = "We Also Count in Google Maps"
[params.feature]
content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
enable = true
title = "We believe in great ideas"
[params.feature.button]
caption = "View Works"
url = "#"
[params.slider]
enable = true
subtitle = "<div style=\"text-align:center;width:100%\">AI&mdash;leveraged solutions for the modern world.</div>"
title = "<div style=\"text-align:center;width:100%\">Exp&ndash;AI</div>"
[params.wrapper]
enable = true
italic = "\"Many of life's failures are people who did not realize how close they were to success when they gave up.\" - Thomas Alva Edison"
paragraph = "Exp-AI is born as an association of former scientists and serial entrepeneurs with a common goal: bring companies closer to the new cognitive era with tailored solutions, specifically designed to get the best possible outcome out of every process and endeavor."
title = "About Us"
