---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections: 
upload_dir: themes/airspace-hugo/static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
version: 0.38.1
